### ISSUE TITLE
add quadlet-podman to manage restarts upon system reboot to ansible playbooks

### ISSUE THREAD

**Issue by DiogoLobo122** [timeseer-ai/timeseer-ansible-collection#14]
- [x] timeseer
- [x] timeseer-reverse-proxy
- [x] timeseer-data-service
- [x] test first run of basic roles
- [x] create branch so jeroen can review
- [x] traefik
- [x] test all roles on first run
- [x] test restart speed pod vs service
- [x] test if pod restart is enough for changing volumes mount

- [x] test the network

**Comment by fombas** [comment]
@lucasKoeb

**Comment by lucasKoeb** [comment]
The quadlet setup is not on master yet. I tried using the collection but the ports config is generating errors:

With `timeseer_ports: "8000:8080"` 
The service fails to start on the host with:
```
jul 16 18:21:49 localhost.localdomain timeseer[7516]: Error: parsing container port: port numbers must be between 1 and 65535 (inclusive), got 0
jul 16 18:21:49 localhost.localdomain systemd[1]: timeseer.service: Main process exited, code=exited, status=125/n/a
jul 16 18:21:49 localhost.localdomain systemd[1]: timeseer.service: Failed with result 'exit-code'.
jul 16 18:21:49 localhost.localdomain systemd[1]: Failed to start timeseer.service.
jul 16 18:21:49 localhost.localdomain systemd[1]: timeseer.service: Scheduled restart job, restart counter is at 5.
jul 16 18:21:49 localhost.localdomain systemd[1]: Stopped timeseer.service.
jul 16 18:21:49 localhost.localdomain systemd[1]: timeseer.service: Start request repeated too quickly.
jul 16 18:21:49 localhost.localdomain systemd[1]: timeseer.service: Failed with result 'exit-code'.
jul 16 18:21:49 localhost.localdomain systemd[1]: Failed to start timeseer.service.
```

And the generated quadlet template that was generated looks like this:
```toml
[Unit]
Wants=network.target
After=network.target

[Container]
ContainerName=timeseer
Image=container.timeseer.ai/timeseer
User=1001
Network=timeseer.network
Volume=/opt/timeseer/data:/usr/src/app/data
Volume=/opt/timeseer/db:/usr/src/app/db:z
Volume=/opt/timeseer/config:/usr/src/app/config/:ro
PublishPort=8
PublishPort=0
PublishPort=0
PublishPort=0
PublishPort=:
PublishPort=8
PublishPort=0
PublishPort=8
PublishPort=0
```
