### ISSUE TITLE
Document `traefik` role variables

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/timeseer-ansible-collection#3]
Most of the important Traefik role variables are not documented:

```yaml
traefik_host: "localhost"
traefik_basic_auth_enable: false
traefik_basic_auth_users: []
traefik_expose_flight: false
traefik_timeseer_reverse_proxy_enable: false
```
