### ISSUE TITLE
Traefik is not restarted after a configuration change

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/timeseer-ansible-collection#4]
The handler only contains:

```yaml
- name: Restart Traefik Container
  ansible.builtin.set_fact:
    traefik_recreate_container: true
  with_items: "{{ traefik_config.results }}"
  when: item is changed
  loop_control:
    label: "{{ item.dest }}"
```

The container itself is not restarted anywhere.
